CREATE TABLE IF NOT EXISTS `public_catalog_import_jobs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `source_name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `total_words` int NOT NULL DEFAULT '0',
  `processed_words` int NOT NULL DEFAULT '0',
  `imported_words` int NOT NULL DEFAULT '0',
  `updated_words` int NOT NULL DEFAULT '0',
  `skipped_words` int NOT NULL DEFAULT '0',
  `failed_words` int NOT NULL DEFAULT '0',
  `refresh_existing` tinyint(1) NOT NULL DEFAULT '0',
  `batch_size` int NOT NULL DEFAULT '150',
  `started_at` timestamp NULL DEFAULT NULL,
  `finished_at` timestamp NULL DEFAULT NULL,
  `created_by_user_id` bigint DEFAULT NULL,
  `error_message` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_public_catalog_import_jobs_status` (`status`,`created_at`),
  KEY `fk_public_catalog_import_jobs_user` (`created_by_user_id`),
  CONSTRAINT `fk_public_catalog_import_jobs_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `public_catalog_import_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `job_id` bigint NOT NULL,
  `word` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempt_count` int NOT NULL DEFAULT '0',
  `last_error` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `entry_id` bigint DEFAULT NULL,
  `has_phonetic` tinyint(1) NOT NULL DEFAULT '0',
  `has_meaning_cn` tinyint(1) NOT NULL DEFAULT '0',
  `has_example` tinyint(1) NOT NULL DEFAULT '0',
  `has_category` tinyint(1) NOT NULL DEFAULT '0',
  `has_audio` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_public_catalog_import_items_job_word` (`job_id`,`word`),
  KEY `idx_public_catalog_import_items_status` (`job_id`,`status`,`id`),
  KEY `fk_public_catalog_import_items_entry` (`entry_id`),
  CONSTRAINT `fk_public_catalog_import_items_entry` FOREIGN KEY (`entry_id`) REFERENCES `vocabulary_entries` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_public_catalog_import_items_job` FOREIGN KEY (`job_id`) REFERENCES `public_catalog_import_jobs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
