spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:4407}/${MYSQL_DATABASE:english_nova}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:english_nova}
    password: ${MYSQL_PASSWORD:english_nova}

server:
  port: ${QUIZ_SERVICE_PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
